<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <OpenTapPackageDefinitionPath>package.xml</OpenTapPackageDefinitionPath>
    <CreateOpenTapPackage>false</CreateOpenTapPackage>
    <CreateOpenTapPackage Condition="'$(Configuration)' == 'Release'">true</CreateOpenTapPackage>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTAP" Version="$(OpenTapVersion)" />
  </ItemGroup>

  <ItemGroup Condition="'$(DebugWith)' == 'TUI' AND '$(Configuration)' == 'Debug'">
    <OpenTapPackageReference Include="TUI" version="1"/>
  </ItemGroup>

  <ItemGroup Condition="'$(DebugWith)' == 'Editor' AND '$(Configuration)' == 'Debug'">
    <OpenTapPackageReference Include="Editor" version="9"/>
  </ItemGroup>
</Project>
