name: CiCd

on: [push]

env:
  OPENTAP_ANSI_COLORS: true
  OPENTAP_NO_UPDATE_CHECK: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_CONSOLE_ANSI_COLOR: true

jobs:
  GetVersion:
    runs-on: ubuntu-latest
    outputs:
      GitVersion: ${{ steps.gitversion.outputs.GitVersion }}
    steps:
      - name: GitVersion
        id: gitversion
        uses: opentap/get-gitversion@main

  Build:
    runs-on: ubuntu-latest
    needs: GetVersion
    env:
      GitVersion: ${{ needs.GetVersion.outputs.GitVersion }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
      - name: Build
        run: dotnet build -c Release
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: tap-package
          retention-days: 7
          path: ProjectName/bin/Release/*.TapPackage

  UnitTests:
    runs-on: ubuntu-latest
    needs: GetVersion
    env:
      GitVersion: ${{ needs.GetVersion.outputs.GitVersion }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
      - name: Test
        run: dotnet test -c Release

  Publish:
    if: github.ref == 'refs/heads/main' || contains(github.ref, 'refs/heads/release') || contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [Build, UnitTests]
    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: tap-package
          path: .
      - name: Setup OpenTAP
        uses: opentap/setup-opentap@v1.2
        with:
          version: $(GitVersion)
          packages: "Repository Client:beta"
      - name: Publish
        run: tap repo upload --repository https://packages.opentap.io --token ${{ secrets.PUBLIC_REPO_PASS }} ProjectName*.TapPackage
