<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <OpenTapPackageDefinitionPath>package.xml</OpenTapPackageDefinitionPath>
    <CreateOpenTapPackage>false</CreateOpenTapPackage>
    <CreateOpenTapPackage Condition="'$(Configuration)' == 'Release'">true</CreateOpenTapPackage>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTAP" Version="$(OpenTapVersion)" />
  </ItemGroup>
</Project>
