<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <OpenTapSetAssemblyVersion>gitversion</OpenTapSetAssemblyVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

    <Configuration Condition="'$(Configuration)' == ''" >Debug</Configuration>
    <OutputPath>$(MSBuildThisFileDirectory)bin\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup>
    <OpenTapVersion>$(GitVersion)</OpenTapVersion>
  </PropertyGroup>
</Project>
