<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;Release</Configurations>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <DebugWith>TapEditor</DebugWith>
  </PropertyGroup>

  <PropertyGroup>
    <OpenTapVersion>$(GitVersion)</OpenTapVersion>
  </PropertyGroup>
</Project>
