<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <PropertyGroup>
    <OpenTapVersion>$(GitVersion)</OpenTapVersion>
  </PropertyGroup>
</Project>
