//            Copyright Keysight Technologies 2012-2025
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, you can obtain one at http://mozilla.org/MPL/2.0/.
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Xml.Linq;
using OpenTap.Cli;

namespace OpenTap.Package.Translation;

/// <summary>
/// This class contains helpful utilities for creating translations of packages.
/// </summary>
[Display("translate", Group: "sdk", Description: "Create a new translation template for a package.")]
public class TranslateAction : ICliAction
{
    /// <summary>
    /// The packages to translate
    /// </summary>
    [UnnamedCommandLineArgument(nameof(Package), Description = "The packages to translate.")]
    [Display("Packages", "The packages to translate")]
    public string[] Packages { get; set; }

    /// <summary>
    /// The language of the translation
    /// </summary>
    [CommandLineArgument("language", ShortName = "l", Description = "The language of the translation.")]
    [Display("Language", "The language of the translation")]
    public string Language { get; set; }

    /// <summary>
    /// Where to put the template
    /// </summary>
    [CommandLineArgument("out", ShortName = "o", Description = "Output file name")]
    public string OutputFileName { get; set; }

    /// <summary>
    /// Whether or not to overwrite existing files
    /// </summary>
    [CommandLineArgument("overwrite", ShortName = "f", Description = "Overwrite existing translation file")]
    public bool Overwrite { get; set; } = false;

    private static readonly TraceSource log = Log.CreateSource("Translate");

    /// <inheritdoc/>
    public int Execute(CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(Language))
        {
            log.Error("Please specify a language.");
            return 1;
        }

        bool cultureKnown;
        CultureInfo culture = CultureInfo.CurrentCulture;
        try
        {
            culture = new CultureInfo(Language);
            cultureKnown = culture.CultureTypes.HasFlag(CultureTypes.UserCustomCulture) == false;
        }
        catch (Exception)
        {
            cultureKnown = false;
        }

        if (!cultureKnown)
        {
            log.Error($"The specified language '{Language}' is not valid. Please provide a two-letter ISO code.");
            return 1;
        }

        log.Info($"Creating {culture.EnglishName} translation template for packages {string.Join(",", Packages)}.");
        var install = Installation.Current;
        var packages = Packages.Select(x => install.FindPackage(x)).ToArray();
        if (packages.Contains(null))
        {
            for (int i = 0; i < packages.Length; i++)
            {
                if (packages[i] == null)
                {
                    log.Error($"Package '{packages[i]}' is not installed.");
                }
            }

            return 1;
        }

        if (string.IsNullOrWhiteSpace(OutputFileName))
        {
            var name = string.Join("-", Packages);
            OutputFileName = Path.Combine(install.Directory, "translations", $"{name}_{culture.TwoLetterISOLanguageName}.xml");
        }

        if (File.Exists(OutputFileName) && Overwrite == false)
        {
            log.Error($"Output file '{OutputFileName}' exists. Please use the '--overwrite' option if you really want to overwrite it.");
            return 1;
        } 

        var opentapPackage = Installation.Current.GetOpenTapPackage();
        var doc = new XDocument();
        string header = $@" Template generated by OpenTAP version {opentapPackage.RawVersion}.

  Please translate the content of all '{TranslationHelpers.DisplayNameAttributeName}' and '{TranslationHelpers.DisplayDescriptionAttributeName}' attributes in this document.
  Everything else should be left as-is, as it is used by OpenTAP to identify what the translation applies to.

  Some terms are best left untranslated. For example, translating well-known SCPI terms is likely to cause confusion,
  but if there is an established translation of a word, the translation should be preferred. Use your best judgment.

  When translating OpenTAP terms, please refer to the official OpenTAP translation, if available, to provide a
  cohesive translation.

  Creating a perfect translation is difficult. If you find that some meaning is lost in the translation, don't be
  afraid to add some clarifying text in the Description element. This will typically be presented to the user in a tooltip.

";
        doc.Add(new XComment(header));
        XElement rootElement = new(TranslationHelpers.TranslationElementName);
        doc.Add(rootElement);
        rootElement.SetAttributeValue(TranslationHelpers.LanguageAttributename, culture.NativeName);
        rootElement.SetAttributeValue(TranslationHelpers.IsoLanguageAttributename, culture.TwoLetterISOLanguageName);
        rootElement.SetAttributeValue(TranslationHelpers.SchemaVersionAttributeName, TranslationHelpers.SchemaVersion.ToString());
        rootElement.SetAttributeValue(TranslationHelpers.OpenTapVersionAttributeName, opentapPackage.RawVersion);

        var types = new List<ITypeData>();
        // first add all plugins
        types.AddRange(TypeData.GetDerivedTypes<ITapPlugin>());
        var pluginTypes = TypeData.GetDerivedTypes<ITapPlugin>();

        // BUG: Enums not correctly discovered
        // BUG: Enum members not correctly discovered
        // TODO: string AvailableValues cannot be supported
        // BUG: Embedded member lookup not working (although embedding works fine)

        static void AddEmbeddedMembers(ITypeData td, HashSet<ITypeData> added)
        {
            try
            { 
                foreach (var mem in td.GetMembers())
                {
                    if (mem.HasAttribute<EmbedPropertiesAttribute>())
                    {
                        // If this type was already added, we are in a recursive loop.
                        // This is okay, we can safely terminate the loop now.
                        if (!added.Add(mem.TypeDescriptor))
                            return;
                        // Embedded members can be recursive
                        AddEmbeddedMembers(mem.TypeDescriptor, added);
                    }
                }
            }
            catch
            {
                // ignore
            }
        }

        // Embedded types are not necessarily plugins. Those must also be added.
        var embeddedTypes = new HashSet<ITypeData>();
        foreach (var plug in pluginTypes)
        {
            AddEmbeddedMembers(plug, embeddedTypes);
        }
        
        types.AddRange(embeddedTypes); 
        // enumTypes are not considered plugins, but should be included.
        types.AddRange(TypeData.GetDerivedTypes<Enum>());

        types = types.Distinct().ToList();

        var typesSources = types.Select(x => TranslationHelpers.GetRelativeFilePathNormalized(install.Directory, x))
            .ToArray();
        
        foreach (var pkg in packages)
        {
            var packageFiles = pkg.Files.Select(x => x.FileName).ToHashSet();
            var packageElement = new XElement(TranslationHelpers.PackageElementName);
            rootElement.Add(packageElement);
            packageElement.SetAttributeValue(TranslationHelpers.PackageNameAttributeName, pkg.Name);
            packageElement.SetAttributeValue(TranslationHelpers.PackageVersionAttributeName, pkg.RawVersion);
            packageElement.SetAttributeValue(TranslationHelpers.DisplayDescriptionAttributeName, pkg.Description);
            List<ITypeData> packageTypes = new();
            {
                for (int i = 0; i < typesSources.Length; i++)
                {
                    if (typesSources[i] == null) continue;
                    if (packageFiles.Contains(typesSources[i]))
                    { 
                        packageTypes.Add(types[i]);
                    }
                }
            }

            var typesBySource =
                packageTypes.GroupBy(tp => TranslationHelpers.GetRelativeFilePathNormalized(install.Directory, tp)); 
            
            foreach (var grp in typesBySource)
            {
                var sourceFile = grp.Key;
                var fileElem = new XElement(TranslationHelpers.FileElementName);
                fileElem.SetAttributeValue(TranslationHelpers.SourceAttributeName, sourceFile);
                foreach (var type in grp)
                {
                    if (skipType(type))
                        continue;
                    var members = type.GetMembers().ToArray();
                    var typename = type.Name;
                    var typeDisplay = type.GetDisplayAttribute();
                    var typeElem = new XElement(TranslationHelpers.TypeElementName);
                    AddDisplayAttributes(typeElem, typeDisplay);
                    typeElem.SetAttributeValue(TranslationHelpers.TypeIdPropertyName, typename);
                    foreach (var mem in members)
                    {
                        if (skipMem(type, mem))
                            continue;
                        var memDisplay = mem.GetDisplayAttribute();
                        var memElem = new XElement(TranslationHelpers.MemberElementName);
                        AddDisplayAttributes(memElem, memDisplay);
                        memElem.SetAttributeValue(TranslationHelpers.PropertyIdAttributeName, mem.Name);
                        var memContainer = EncapsulateInGroup(memElem, memDisplay);
                        typeElem.Add(memContainer);
                    }
                    MergeGroupElements(typeElem); 
                    var typeContainer = EncapsulateInGroup(typeElem, typeDisplay); 
                    fileElem.Add(typeContainer);
                } 
                MergeGroupElements(fileElem);
                packageElement.Add(fileElem);
            }
        }

        try
        {
            var outdir = Path.GetDirectoryName(OutputFileName);
            if (!string.IsNullOrWhiteSpace(outdir))
                Directory.CreateDirectory(outdir);
            using (var fs = File.Open(OutputFileName, FileMode.Create, FileAccess.Write))
                doc.Save(fs);
            log.Info($"Wrote template to '{OutputFileName}'.");
        }
        catch (Exception ex)
        {
            log.Error($"Error saving template: {ex.Message}");
            return 1;
        }

        return 0;
    }
    static bool skipType(ITypeData type)
    {
        // Skip types that cannot be instantiated if they do not have any members.
        if (!type.CanCreateInstance && !type.GetMembers().Any(mem => !skipMem(type, mem)))
            return true;
        return false;
    }

    static bool skipMem(ITypeData type, IMemberData mem)
    {
        // If this member is inherited, the translation should happen in the base class.
        if (mem.DeclaringType != type) return true;
        return false;
    }

    static void AddDisplayAttributes(XElement element, DisplayAttribute disp)
    { 
        element.SetAttributeValue(TranslationHelpers.DisplayNameAttributeName, disp.Name);
        element.SetAttributeValue(TranslationHelpers.DisplayDescriptionAttributeName, disp.Description);
        if (Math.Abs(disp.Order - DisplayAttribute.DefaultOrder) > 0.1)
            element.SetAttributeValue(TranslationHelpers.DisplayOrderAttributeName, disp.Order);
    }

    static XElement EncapsulateInGroup(XElement element, DisplayAttribute disp)
    {
        var root = element;
        foreach (var grp in disp.Group.Reverse())
        {
            var elm = new XElement(TranslationHelpers.DisplayGroupElementName);
            elm.SetAttributeValue(TranslationHelpers.DisplayNameAttributeName, grp); 
            elm.Add(root);
            root = elm;
        }

        return root;
    }

    static void MergeGroupElements(XElement root)
    {
        var groups = root.Elements(TranslationHelpers.DisplayGroupElementName)
            .GroupBy(g => g.Attribute(TranslationHelpers.DisplayNameAttributeName).Value);

        foreach (var g in groups)
        {
            var elems = g.ToArray();
            if (elems.Length < 2) continue;
            var fst = elems.First();
            // Transplant children of other elements into this one
            foreach (var e in elems.Skip(1))
            { 
                foreach (var sub in e.Elements())
                {
                    fst.Add(sub); 
                }
                e.Remove();
            }
            // Merge subgroups in the new super element
            MergeGroupElements(fst);
        }
    }
}

