//            Copyright Keysight Technologies 2012-2025
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, you can obtain one at http://mozilla.org/MPL/2.0/.
using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Xml.Linq;
using OpenTap.Cli;

namespace OpenTap.Package.Translation;

/// <summary>
/// This class contains helpful utilities for creating translations of packages.
/// </summary>
[Display("translate", Group: "sdk", Description: "Create a new translation template for a package.")]
public class TranslateAction : ICliAction
{
    /// <summary>
    /// The packages to translate
    /// </summary>
    [UnnamedCommandLineArgument(nameof(Package), Description = "The packages to translate.")]
    [Display("Packages", "The packages to translate")]
    public string[] Packages { get; set; }

    /// <summary>
    /// The language of the translation
    /// </summary>
    [CommandLineArgument("language", ShortName = "l", Description = "The language of the translation.")]
    [Display("Language", "The language of the translation")]
    public string Language { get; set; }

    /// <summary>
    /// Where to put the template
    /// </summary>
    [CommandLineArgument("out", ShortName = "o", Description = "Output file name")]
    public string OutputFileName { get; set; }

    /// <summary>
    /// Whether or not to overwrite existing files
    /// </summary>
    [CommandLineArgument("overwrite", ShortName = "f", Description = "Overwrite existing translation file")]
    public bool Overwrite { get; set; } = false;

    private static readonly TraceSource log = Log.CreateSource("Translate");

    /// <inheritdoc/>
    public int Execute(CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(Language))
        {
            log.Error("Please specify a language.");
            return 1;
        }

        bool cultureKnown;
        CultureInfo culture = CultureInfo.CurrentCulture;
        try
        {
            culture = new CultureInfo(Language);
            cultureKnown = culture.CultureTypes.HasFlag(CultureTypes.UserCustomCulture) == false;
        }
        catch (Exception)
        {
            cultureKnown = false;
        }

        if (!cultureKnown)
        {
            log.Error($"The specified language '{Language}' is not valid. Please provide a two-letter ISO code.");
            return 1;
        }

        log.Info($"Creating {culture.EnglishName} translation template for packages {string.Join(",", Packages)}.");
        var install = Installation.Current;
        var packages = Packages.Select(x => install.FindPackage(x)).ToArray();
        if (packages.Contains(null))
        {
            for (int i = 0; i < packages.Length; i++)
            {
                if (packages[i] == null)
                {
                    log.Error($"Package '{packages[i]}' is not installed.");
                }
            }

            return 1;
        }

        if (string.IsNullOrWhiteSpace(OutputFileName))
        {
            var name = string.Join("-", Packages);
            OutputFileName = Path.Combine(install.Directory, "translations", $"{name}_{culture.TwoLetterISOLanguageName}.xml");
        }

        if (File.Exists(OutputFileName) && Overwrite == false)
        {
            log.Error($"Output file '{OutputFileName}' exists. Please use the '--overwrite' option if you really want to overwrite it.");
        } 

        var opentapPackage = Installation.Current.GetOpenTapPackage();
        var doc = new XDocument();
        string header = $@" Template generated by OpenTAP version {opentapPackage.RawVersion}.

  Please translate the content of all '{TranslationHelpers.DisplayNameAttributeName}' and '{TranslationHelpers.DisplayDescriptionAttributeName}' attributes in this document.
  Everything else should be left as-is, as it is used by OpenTAP to identify what the translation applies to.

  Some terms are best left untranslated. For example, translating well-known SCPI terms is likely to cause confusion,
  but if there is an established translation of a word, the translation should be preferred. Use your best judgment.

  When translating OpenTAP terms, please refer to the official OpenTAP translation, if available, to provide a
  cohesive translation.

  Creating a perfect translation is difficult. If you find that some meaning is lost in the translation, don't be
  afraid to add some clarifying text in the Description element. This will typically be presented to the user in a tooltip.

";
        doc.Add(new XComment(header));
        XElement translationElement = new(TranslationHelpers.TranslationElementName);
        doc.Add(translationElement);
        translationElement.SetAttributeValue(TranslationHelpers.LanguageAttributename, culture.NativeName);
        translationElement.SetAttributeValue(TranslationHelpers.IsoLanguageAttributename, culture.TwoLetterISOLanguageName);

        foreach (var pkg in packages)
        {
            var packageElement = new XElement(TranslationHelpers.PackageElementName);
            translationElement.Add(packageElement);
            packageElement.SetAttributeValue(TranslationHelpers.PackageNameAttributeName, pkg.Name);
            packageElement.SetAttributeValue(TranslationHelpers.PackageVersionAttributeName, pkg.RawVersion);
            packageElement.SetAttributeValue(TranslationHelpers.DisplayDescriptionAttributeName, pkg.Description);
            var packageTypes = TypeData.GetDerivedTypes<ITapPlugin>()
                .Where(x => install.FindPackageContainingType(x) == pkg).ToArray();

            var typesBySource =
                packageTypes.GroupBy(tp => TranslationHelpers.GetRelativeFilePathNormalized(install.Directory, tp));

            static bool skipType(ITypeData type)
            {
                // Skip types that cannot be instantiated if they do not have any members.
                if (!type.CanCreateInstance && !type.GetMembers().Any(mem => !skipMem(type, mem)))
                    return true;
                return false;
            }

            static bool skipMem(ITypeData type, IMemberData mem)
            {
                // If this member is inherited, the translation should happen in the base class.
                if (mem.DeclaringType != type) return true;
                return false;
            }

            static void AddDisplayAttributes(XElement element, DisplayAttribute disp)
            { 
                element.SetAttributeValue(TranslationHelpers.DisplayNameAttributeName, disp.Name);
                element.SetAttributeValue(TranslationHelpers.DisplayDescriptionAttributeName, disp.Description);
                if (Math.Abs(disp.Order - DisplayAttribute.DefaultOrder) > 0.1)
                    element.SetAttributeValue(TranslationHelpers.DisplayOrderAttributeName, disp.Order);
            }

            static XElement EncapsulateInGroup(XElement element, DisplayAttribute disp)
            {
                var root = element;
                foreach (var grp in disp.Group.Reverse())
                {
                    var elm = new XElement(TranslationHelpers.DisplayGroupElementName);
                    elm.SetAttributeValue(TranslationHelpers.DisplayNameAttributeName, grp); 
                    elm.Add(root);
                    root = elm;
                }

                return root;
            }

            static void MergeGroupElements(XElement root)
            {
                var groups = root.Elements(TranslationHelpers.DisplayGroupElementName)
                    .GroupBy(g => g.Attribute(TranslationHelpers.DisplayNameAttributeName).Value);

                foreach (var g in groups)
                {
                    var elems = g.ToArray();
                    if (elems.Length < 2) continue;
                    var fst = elems.First();
                    // Transplant children of other elements into this one
                    foreach (var e in elems.Skip(1))
                    { 
                        foreach (var sub in e.Elements())
                        {
                            fst.Add(sub); 
                        }
                        e.Remove();
                    }
                    // Merge subgroups in the new super element
                    MergeGroupElements(fst);
                }
            }
            
            foreach (var grp in typesBySource)
            {
                var sourceFile = grp.Key;
                var fileElem = new XElement(TranslationHelpers.FileElementName);
                fileElem.SetAttributeValue(TranslationHelpers.SourceAttributeName, sourceFile);
                foreach (var type in grp)
                {
                    if (skipType(type))
                        continue;
                    var members = type.GetMembers().ToArray();
                    var typename = type.Name;
                    var typeDisplay = type.GetDisplayAttribute();
                    var typeElem = new XElement(TranslationHelpers.TypeElementName);
                    AddDisplayAttributes(typeElem, typeDisplay);
                    typeElem.SetAttributeValue(TranslationHelpers.TypeIdPropertyName, typename);
                    foreach (var mem in members)
                    {
                        if (skipMem(type, mem))
                            continue;
                        var memDisplay = mem.GetDisplayAttribute();
                        var memElem = new XElement(TranslationHelpers.MemberElementName);
                        AddDisplayAttributes(memElem, memDisplay);
                        memElem.SetAttributeValue(TranslationHelpers.PropertyIdAttributeName, mem.Name);
                        var memContainer = EncapsulateInGroup(memElem, memDisplay);
                        typeElem.Add(memContainer);
                    }
                    MergeGroupElements(typeElem); 
                    var typeContainer = EncapsulateInGroup(typeElem, typeDisplay); 
                    fileElem.Add(typeContainer);
                } 
                MergeGroupElements(fileElem);
                packageElement.Add(fileElem);
            }
        }

        try
        {
            var outdir = Path.GetDirectoryName(OutputFileName);
            if (!string.IsNullOrWhiteSpace(outdir))
                Directory.CreateDirectory(outdir);
            using (var fs = File.Open(OutputFileName, FileMode.Create, FileAccess.Write))
                doc.Save(fs);
            log.Info($"Wrote template to '{OutputFileName}'.");
        }
        catch (Exception ex)
        {
            log.Error($"Error saving template: {ex.Message}");
            return 1;
        }

        return 0;
    }
}

