//            Copyright Keysight Technologies 2012-2025
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, you can obtain one at http://mozilla.org/MPL/2.0/.
using System;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Xml.Linq;
using OpenTap.Cli;

namespace OpenTap.Package.Translation;

/// <summary>
/// This class contains helpful utilities for creating translations of packages.
/// </summary>
[Display("translate", Group: "sdk", Description: "Create a new translation template for a package.")]
public class TranslateAction : ICliAction
{
    /// <summary>
    /// The package to translate
    /// </summary>
    [UnnamedCommandLineArgument(nameof(Package), Description = "The package to translate.")]
    public string Package { get; set; }

    /// <summary>
    /// The language of the translation
    /// </summary>
    [CommandLineArgument("language", ShortName = "l", Description = "The language of the translation.")]
    [Display("Language", "The language of the translation")]
    public string Language { get; set; }

    /// <summary>
    /// Where to put the template
    /// </summary>
    [CommandLineArgument("out", ShortName = "o", Description = "Output file name")]
    public string OutputFileName { get; set; }

    private static readonly TraceSource log = Log.CreateSource("Translate");

    /// <inheritdoc/>
    public int Execute(CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(Language))
        {
            log.Error("Please specify a language.");
            return 1;
        }

        bool cultureKnown;
        CultureInfo culture = CultureInfo.CurrentCulture;
        try
        {
            culture = new CultureInfo(Language);
            cultureKnown = culture.CultureTypes.HasFlag(CultureTypes.UserCustomCulture) == false;
        }
        catch (Exception)
        {
            cultureKnown = false;
        }

        if (!cultureKnown)
        {
            log.Error($"The specified language '{Language}' is not valid. Please provide a two-letter ISO code.");
            return 1;
        }

        log.Info($"Creating translation template for package '{Package}' to language '{culture.TwoLetterISOLanguageName}' ({culture.NativeName}).");
        var install = Installation.Current;
        var pkg = install.FindPackage(Package);
        if (pkg == null)
        {
            log.Error($"Package {Package} is not installed.");
            return 1;
        }

        if (string.IsNullOrWhiteSpace(OutputFileName))
        {
            OutputFileName = $"{pkg.Name}_{culture.TwoLetterISOLanguageName}.xml";
        }

        var packageTypes = TypeData.GetDerivedTypes<ITapPlugin>()
            .Where(x => install.FindPackageContainingType(x) == pkg).ToArray();

        var typesBySource = packageTypes.GroupBy(tp => TranslationHelpers.GetRelativeFilePathNormalized(install, tp));

        var opentapPackage = Installation.Current.GetOpenTapPackage();
        var doc = new XDocument();
        string header = $@" Template generated by OpenTAP version {opentapPackage.RawVersion}.

  Please translate the content of all '{TranslationHelpers.DisplayNameAttributeName}' and '{TranslationHelpers.DisplayDescriptionAttributeName}' attributes in this document.
  Everything else should be left as-is, as it is used by OpenTAP to identify what the translation applies to.

  Some terms are best left untranslated. For example, translating well-known SCPI terms is likely to cause confusion,
  but if there is an established translation of a word, the translation should be preferred. Use your best judgment.

  When translating OpenTAP terms, please refer to the official OpenTAP translation, if available, to provide a
  cohesive translation.

  Creating a perfect translation is difficult. If you find that some meaning is lost in the translation, don't be
  afraid to add some clarifying text in the Description element. This will typically be presented to the user in a tooltip.

";
        doc.Add(new XComment(header));
        XElement rootElement = new(TranslationHelpers.RootElementName);
        doc.Add(rootElement);
        rootElement.SetAttributeValue(TranslationHelpers.PackageNameAttribute, pkg.Name);
        rootElement.SetAttributeValue(TranslationHelpers.LanguageAttributename, culture.NativeName);
        rootElement.SetAttributeValue(TranslationHelpers.IsoLanguageAttributename, culture.TwoLetterISOLanguageName);
        rootElement.SetAttributeValue(TranslationHelpers.DisplayDescriptionAttributeName, pkg.Description);

        static bool skipType(ITypeData type)
        {
            // Skip types that cannot be instantiated if they do not have any members.
            if (!type.CanCreateInstance && !type.GetMembers().Any(mem => !skipMem(type, mem)))
                return true;
            return false;
        }
        static bool skipMem(ITypeData type, IMemberData mem)
        {
            // If this member is inherited, the translation should happen in the base class.
            if (mem.DeclaringType != type) return true;
            return false;
        }

        var sw = Stopwatch.StartNew();
        foreach (var grp in typesBySource)
        {
            var sourceFile = grp.Key;
            var elem = new XElement(TranslationHelpers.FileElementName);
            elem.SetAttributeValue(TranslationHelpers.SourceAttributeName, sourceFile);
            foreach (var type in grp)
            {
                if (skipType(type))
                    continue;
                var members = type.GetMembers().ToArray();
                var typename = type.Name;
                var display = type.GetDisplayAttribute();
                var typeElem = new XElement(TranslationHelpers.TypeElementName);
                typeElem.SetAttributeValue(TranslationHelpers.DisplayNameAttributeName, display.Name);
                typeElem.SetAttributeValue(TranslationHelpers.DisplayDescriptionAttributeName, display.Description);
                typeElem.SetAttributeValue(TranslationHelpers.TypeIdPropertyName, typename);
                foreach (var mem in members)
                {
                    if (skipMem(type, mem))
                        continue;
                    var memDisplay = mem.GetDisplayAttribute();
                    var memElem = new XElement(TranslationHelpers.MemberElementName);
                    memElem.SetAttributeValue(TranslationHelpers.DisplayNameAttributeName, memDisplay.Name);
                    memElem.SetAttributeValue(TranslationHelpers.DisplayDescriptionAttributeName, memDisplay.Description);
                    memElem.SetAttributeValue(TranslationHelpers.PropertyIdAttributeName, mem.Name);
                    typeElem.Add(memElem);
                }
                elem.Add(typeElem);
            }
            rootElement.Add(elem);
        }

        try
        {
            using (var fs = File.Open(OutputFileName, FileMode.Create, FileAccess.Write))
                doc.Save(fs);
            log.Info($"Wrote template to '{OutputFileName}'.");
        }
        catch (Exception ex)
        {
            log.Error($"Error saving template: {ex.Message}");
            return 1;
        }

        return 0;
    }
}

/// <inheritdoc/>
public class SomeStep : TestStep
{
    /// <inheritdoc/>
    public override void Run()
    {
    }
}
